### ISSUE TITLE
python2 error

### ISSUE THREAD

**Issue by jinfagang** [gunthercox/chatterbot-corpus#109]
```
  "chatterbot.corpus.english.conversations"
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/trainers.py", line 143, in train
    corpora = self.corpus.load_corpus(corpus_path)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot_corpus/corpus.py", line 87, in load_corpus
    data_file_paths = self.list_corpus_files(dotted_path)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot_corpus/corpus.py", line 76, in list_corpus_files
    paths = glob.glob(corpus_path + '/**/*.' + CORPUS_EXTENSION, recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'

```

**Comment by vkosuri** [comment]
I think `recursive` won't support in `python2`, try to upgrade to `python3`

**Comment by jinfagang** [comment]
@vkosuri I am using in ROS, which only support python2, does there an compatible way to do this?

**Comment by vkosuri** [comment]
``pip install chaterbot ==0.8.0``

**Comment by amitassaraf** [comment]
Why is there no python2 support for the new versions of Chatterbot?

**Comment by gunthercox** [comment]
I removed Python 2 support in the new version to make ChatterBot easier to maintain. Many other Python projects are ending their support for Python 2 as well, such as @django. The choice to end support for Python 2 was not done lightly since I am well aware that there are still many projects that are still dependent on it.
