### ISSUE TITLE
What function does Extra Data mean?

### ISSUE THREAD

**Issue by Issen007** [gunthercox/chatterbot-corpus#37]
As you probably already understand I'm really start playing around with your cool project. (Thanks for your great work).

But what does the field `Extra Data` mean when I create my own Statement/Respond?

Thanks

**Comment by gunthercox** [comment]
The `extra_data` attribute was added to ChatterBot's Statement models as an early attempt to allow developers to store additional information about a statement. I don't recommend using it because it is going to be removed in the near future. The alternate, and much better solution that will replace it will be the ability to override ChatterBot's statement models with custom ones so that additional fields can be added to those models.

`extra_data` isn't related to the dialog data contained within the `chatterbot-corpus` module.

**Comment by Issen007** [comment]
@gunthercox thanks, that mean we should then tell the moduls.py that the extra data field can be blank when you create your own statement from the Django Admin.

I have fix that on my own and I can also do a pull request on that and modify it for you.

**Comment by gunthercox** [comment]
Okay, thank you. I'll take a look.

**Comment by Issen007** [comment]
@gunthercox this is what my pull request [#941](https://github.com/gunthercox/ChatterBot/pull/941) is fixing.
