### ISSUE TITLE
how are you?

### ISSUE THREAD

**Issue by itskeyes** [gunthercox/chatterbot-corpus#45]
For some reason, during conversations 'how are you' triggers the 'who are you' response.

**Comment by Issen007** [comment]
@itskeyes this is probably just during teaching period and this is what AI is all about.
In the beginning is Chatterbot and other AI chatbots extremally “unknowledgeble” and this is where your work comes in to train it.

**Comment by vkosuri** [comment]
@itskeyes as @Issen007 said is correct, The bot will learn users correct response over a period of training.

However you could see the bot is selecting responses to get more sight on your response tracking by enabling logging.

``` Python
# Uncomment the following lines to enable verbose logging
import logging
logging.basicConfig(level=logging.INFO)
```

Even you could restrict wrong response by setting [threshold ](http://chatterbot.readthedocs.io/en/stable/logic/index.html#low-confidence-response-adapter) to response, so that you may see correct response getting.

Happy chatting 👍

**Comment by itskeyes** [comment]
Thanks everyone for the input! Will continue working through the documentation and by testing.
